FROM python:3-slim

RUN apt-get update && apt-get install -y \
    make \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /docs

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV SPHINXBUILD=sphinx-build

CMD ["make", "html"]
