FROM python:3-slim

RUN apt-get update && apt-get install -y \
    make \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -u 1000 -m -s /bin/bash user

WORKDIR /docs

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN chown -R user:user /docs
USER user

ENV SPHINXBUILD=sphinx-build

CMD ["make", "html"]
